version: '3'

services:
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: vehicledb
      POSTGRES_USER: postgresUser
      POSTGRES_PASSWORD: postgresPassword
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./sql_scripts:/docker-entrypoint-initdb.d
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 3GB

  vehicle-api1:
    image: dkovacs/vehicles:latest
    ports:
      - "8082:8080"
      - "50055:5005"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/vehicledb
      SPRING_DATASOURCE_USERNAME: postgresUser
      SPRING_DATASOURCE_PASSWORD: postgresPassword
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 2GB

  vehicle-api2:
    image: dkovacs/vehicles:latest
    ports:
      - "8083:8080"
      - "50056:5005"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/vehicledb
      SPRING_DATASOURCE_USERNAME: postgresUser
      SPRING_DATASOURCE_PASSWORD: postgresPassword
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 2GB

  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    depends_on:
      - vehicle-api1
      - vehicle-api2
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 1GB

volumes:
  postgres_data: